In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from copy import deepcopy

In [4]:
dff = pd.read_csv("C:\\Users\\91909\\Downloads\\train.csv\\train.csv")
dss = pd.read_csv("C:\\Users\\91909\\Downloads\\test.csv\\test.csv")

In [5]:
dff

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54268,54268,BMW,X6 xDrive50i,2017,29000,Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Brown,None reported,Yes,29000
54269,54269,Audi,A4 2.0T Premium,2015,94634,E85 Flex Fuel,220.0HP 2.0L 4 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,6500
54270,54270,Porsche,Cayenne S,2013,40989,Gasoline,420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,At least 1 accident or damage reported,Yes,18950
54271,54271,Porsche,911 Carrera 4 GTS,2023,1518,Gasoline,4.0L H6 24V GDI DOHC,8-Speed Automatic with Auto-Shift,Beige,Brown,None reported,Yes,194965
54272,54272,Audi,A5 Sportback S line Premium Plus,2021,35000,Hybrid,261.0HP 2.0L 4 Cylinder Engine Gasoline/Mild E...,8-Speed A/T,Black,Black,None reported,Yes,37499

In [6]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54273 entries, 0 to 54272
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            54273 non-null  int64
 1   brand         54273 non-null  object
 2   model         54273 non-null  object
 3   model_year    54273 non-null  int64
 4   milage        54273 non-null  int64
 5   fuel_type     54273 non-null  object
 6   engine        54273 non-null  object
 7   transmission  54273 non-null  object
 8   ext_col       54273 non-null  object
 9   int_col       54273 non-null  object
 10  accident      54273 non-null  object
 11  clean_title   54273 non-null  object
 12  price         54273 non-null  int64
dtypes: int64(4), object(9)
memory usage: 5.4+ MB

In [7]:
dff.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [8]:
df = deepcopy(dff[['brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price']])

In [9]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850
...,...,...,...,...,...,...,...,...,...,...,...,...
54268,BMW,X6 xDrive50i,2017,29000,Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Brown,None reported,Yes,29000
54269,Audi,A4 2.0T Premium,2015,94634,E85 Flex Fuel,220.0HP 2.0L 4 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,6500
54270,Porsche,Cayenne S,2013,40989,Gasoline,420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,At least 1 accident or damage reported,Yes,18950
54271,Porsche,911 Carrera 4 GTS,2023,1518,Gasoline,4.0L H6 24V GDI DOHC,8-Speed Automatic with Auto-Shift,Beige,Brown,None reported,Yes,194965
54272,Audi,A5 Sportback S line Premium Plus,2021,35000,Hybrid,261.0HP 2.0L 4 Cylinder Engine Gasoline/Mild E...,8-Speed A/T,Black,Black,None reported,Yes,37499

In [10]:
df.brand = df.brand.astype('category').cat.codes
df.model = df.model.astype('category').cat.codes
df.fuel_type = df.fuel_type.astype('category').cat.codes
df.engine = df.engine.astype('category').cat.codes
df.transmission = df.transmission.astype('category').cat.codes
df.ext_col = df.ext_col.astype('category').cat.codes
df.int_col = df.int_col.astype('category').cat.codes
df.accident = df.accident.astype('category').cat.codes
df.clean_title = df.fuel_type.astype('category').cat.codes

In [11]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,14,644,2018,74349,2,719,2,26,57,1,2,11000
1,4,49,2007,80000,2,534,18,17,9,1,2,8250
2,21,1771,2009,91491,2,541,14,181,6,1,2,15000
3,4,1748,2022,2437,3,646,43,100,24,1,3,63500
4,40,693,2001,111000,2,219,34,249,9,1,2,7850
...,...,...,...,...,...,...,...,...,...,...,...,...
54268,4,1745,2017,29000,2,856,27,249,24,1,2,29000
54269,3,165,2015,94634,1,266,14,17,9,0,1,6500
54270,41,421,2013,40989,2,817,43,249,9,0,2,18950
54271,41,142,2023,1518,2,762,29,12,24,1,2,194965
54272,3,176,2021,35000,3,372,27,17,9,1,3,37499

In [12]:
x_train = df.to_numpy()[:, :-1]
y_train = df.to_numpy()[:, -1]

model = LinearRegression()
model.fit(x_train, y_train)
# y_predict = model.predict(x_test)
# rmse = np.sqrt(mean_squared_error(y_test, y_predict))
# ac = model.score(x_test, y_test)
model

LinearRegression()

In [13]:
model.coef_

array([ 1.38439033e+02, -1.39761031e+00,  1.01310381e+03, -2.07843161e-01,
       -1.23524304e+03,  3.98480115e+01, -2.70347922e+01, -2.28640309e+00,
        6.49447544e+01,  5.28719005e+03, -1.23524304e+03])

In [14]:
df['prediction'] = model.predict(x_train)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,prediction
0,14,644,2018,74349,2,719,2,26,57,1,2,11000,51758.859113
1,4,49,2007,80000,2,534,18,17,9,1,2,8250,27986.173928
2,21,1771,2009,91491,2,541,14,181,6,1,2,15000,27388.105266
3,4,1748,2022,2437,3,646,43,100,24,1,3,63500,59030.151540
4,40,693,2001,111000,2,219,34,249,9,1,2,7850,6033.031418
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54268,4,1745,2017,29000,2,856,27,249,24,1,2,29000,59378.338527
54269,3,165,2015,94634,1,266,14,17,9,0,1,6500,19361.033872
54270,41,421,2013,40989,2,817,43,249,9,0,2,18950,51558.781415
54271,41,142,2023,1518,2,762,29,12,24,1,2,194965,75273.615572
54272,3,176,2021,35000,3,372,27,17,9,1,3,37499,42037.456918

In [15]:
mean_absolute_error(df['price'], df['prediction'])

19589.4768872285

In [24]:
dss

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
36178,90451,GMC,Yukon Denali,2019,4500,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,None reported,Yes
36179,90452,Chevrolet,Silverado 1500 Z71 Extended Cab,2004,185000,Gasoline,295.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,4-Speed A/T,Red,Gray,At least 1 accident or damage reported,Yes
36180,90453,Toyota,Corolla LE,2011,116000,Gasoline,132.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Beige,Gray,None reported,Yes
36181,90454,Lincoln,Navigator Reserve,2019,39000,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Orange,None reported,Yes
36182,90455,Chevrolet,Tahoe LT,2012,162731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Black,Black,At least 1 accident or damage reported,Yes

In [25]:
ds = deepcopy(dss[['brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title']])

In [26]:
ds.brand = ds.brand.astype('category').cat.codes
ds.model = ds.model.astype('category').cat.codes
ds.fuel_type = ds.fuel_type.astype('category').cat.codes
ds.engine = ds.engine.astype('category').cat.codes
ds.transmission = ds.transmission.astype('category').cat.codes
ds.ext_col = ds.ext_col.astype('category').cat.codes
ds.int_col = ds.int_col.astype('category').cat.codes
ds.accident = ds.accident.astype('category').cat.codes
ds.clean_title = ds.fuel_type.astype('category').cat.codes

In [27]:
ds

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,34,528,2014,73000,2,544,33,220,8,1,2
1,26,1246,2015,128032,2,410,26,187,10,1,2
2,34,317,2015,51983,2,311,20,26,107,1,2
3,25,1318,2018,29500,2,911,42,220,107,0,2
4,4,1710,2020,90000,2,633,26,220,10,0,2
...,...,...,...,...,...,...,...,...,...,...,...
36178,15,1763,2019,4500,2,807,2,88,10,1,2
36179,9,1481,2004,185000,2,473,7,163,53,0,2
36180,49,480,2011,116000,2,30,11,12,53,1,2
36181,27,1082,2019,39000,2,843,2,17,82,1,2
36182,9,1575,2012,162731,1,601,33,17,10,0,1

In [28]:
x_test = ds.to_numpy()
x_test

array([[  34,  528, 2014, ...,    8,    1,    2],
       [  26, 1246, 2015, ...,   10,    1,    2],
       [  34,  317, 2015, ...,  107,    1,    2],
       ...,
       [  49,  480, 2011, ...,   53,    1,    2],
       [  27, 1082, 2019, ...,   82,    1,    2],
       [   9, 1575, 2012, ...,   10,    0,    1]], dtype=int64)

In [29]:
dss['prediction'] = model.predict(x_test)
dss

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,prediction
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes,39480.392031
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes,21999.425334
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes,43096.589849
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes,65747.169052
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,34798.950782
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36178,90451,GMC,Yukon Denali,2019,4500,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,None reported,Yes,66176.577558
36179,90452,Chevrolet,Silverado 1500 Z71 Extended Cab,2004,185000,Gasoline,295.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,4-Speed A/T,Red,Gray,At least 1 accident or damage reported,Yes,-3082.633944
36180,90453,Toyota,Corolla LE,2011,116000,Gasoline,132.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Beige,Gray,None reported,Yes,13158.468779
36181,90454,Lincoln,Navigator Reserve,2019,39000,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Orange,None reported,Yes,67891.914857
36182,90455,Chevrolet,Tahoe LT,2012,162731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Black,Black,At least 1 accident or damage reported,Yes,13928.597884

In [30]:
dss[['id', 'prediction']].to_csv('My_Model.csv', index = False)